import {Participant} from './participant'

export interface IStrategy {
  HARD: object
  SOFT: object
  PAIRS: object
}

export const SIX_DECK_H17_DAS_NO_SURR: IStrategy = {
  HARD: {
    // Outside key is value of dealers upcard, ace == 11
    // Inside key is total value of players hand
    2: {
      5: Participant.actions.HIT,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.HIT,
      9: Participant.actions.HIT,
      10: Participant.actions.DOUBLE,
      11: Participant.actions.DOUBLE,
      12: Participant.actions.HIT,
      13: Participant.actions.STAND,
      14: Participant.actions.STAND,
      15: Participant.actions.STAND,
      16: Participant.actions.STAND,
      17: Participant.actions.STAND,
      18: Participant.actions.STAND,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    3: {
      5: Participant.actions.HIT,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.HIT,
      9: Participant.actions.DOUBLE,
      10: Participant.actions.DOUBLE,
      11: Participant.actions.DOUBLE,
      12: Participant.actions.HIT,
      13: Participant.actions.STAND,
      14: Participant.actions.STAND,
      15: Participant.actions.STAND,
      16: Participant.actions.STAND,
      17: Participant.actions.STAND,
      18: Participant.actions.STAND,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    4: {
      5: Participant.actions.HIT,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.HIT,
      9: Participant.actions.DOUBLE,
      10: Participant.actions.DOUBLE,
      11: Participant.actions.DOUBLE,
      12: Participant.actions.STAND,
      13: Participant.actions.STAND,
      14: Participant.actions.STAND,
      15: Participant.actions.STAND,
      16: Participant.actions.STAND,
      17: Participant.actions.STAND,
      18: Participant.actions.STAND,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    5: {
      5: Participant.actions.HIT,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.HIT,
      9: Participant.actions.DOUBLE,
      10: Participant.actions.DOUBLE,
      11: Participant.actions.DOUBLE,
      12: Participant.actions.STAND,
      13: Participant.actions.STAND,
      14: Participant.actions.STAND,
      15: Participant.actions.STAND,
      16: Participant.actions.STAND,
      17: Participant.actions.STAND,
      18: Participant.actions.STAND,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    6: {
      5: Participant.actions.HIT,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.HIT,
      9: Participant.actions.DOUBLE,
      10: Participant.actions.DOUBLE,
      11: Participant.actions.DOUBLE,
      12: Participant.actions.STAND,
      13: Participant.actions.STAND,
      14: Participant.actions.STAND,
      15: Participant.actions.STAND,
      16: Participant.actions.STAND,
      17: Participant.actions.STAND,
      18: Participant.actions.STAND,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    7: {
      5: Participant.actions.HIT,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.HIT,
      9: Participant.actions.HIT,
      10: Participant.actions.DOUBLE,
      11: Participant.actions.DOUBLE,
      12: Participant.actions.HIT,
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.HIT,
      16: Participant.actions.HIT,
      17: Participant.actions.STAND,
      18: Participant.actions.STAND,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    8: {
      5: Participant.actions.HIT,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.HIT,
      9: Participant.actions.HIT,
      10: Participant.actions.DOUBLE,
      11: Participant.actions.DOUBLE,
      12: Participant.actions.HIT,
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.HIT,
      16: Participant.actions.HIT,
      17: Participant.actions.STAND,
      18: Participant.actions.STAND,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    9: {
      5: Participant.actions.HIT,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.HIT,
      9: Participant.actions.HIT,
      10: Participant.actions.DOUBLE,
      11: Participant.actions.DOUBLE,
      12: Participant.actions.HIT,
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.HIT,
      16: Participant.actions.HIT,
      17: Participant.actions.STAND,
      18: Participant.actions.STAND,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    10: {
      5: Participant.actions.HIT,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.HIT,
      9: Participant.actions.HIT,
      10: Participant.actions.HIT,
      11: Participant.actions.DOUBLE,
      12: Participant.actions.HIT,
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.HIT,
      16: Participant.actions.HIT,
      17: Participant.actions.STAND,
      18: Participant.actions.STAND,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    11: {
      5: Participant.actions.HIT,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.HIT,
      9: Participant.actions.HIT,
      10: Participant.actions.HIT,
      11: Participant.actions.DOUBLE,
      12: Participant.actions.HIT,
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.HIT,
      16: Participant.actions.HIT,
      17: Participant.actions.STAND,
      18: Participant.actions.STAND,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
  },
  PAIRS: {
    // Outside key is value of dealers upcard, ace == 11
    // Inside key value of one card in the pair, ace == 11
    2: {
      2: Participant.actions.SPLIT,
      3: Participant.actions.SPLIT,
      4: Participant.actions.HIT,
      5: Participant.actions.DOUBLE,
      6: Participant.actions.SPLIT,
      7: Participant.actions.SPLIT,
      8: Participant.actions.SPLIT,
      9: Participant.actions.SPLIT,
      10: Participant.actions.STAND,
      11: Participant.actions.SPLIT,
    },
    3: {
      2: Participant.actions.SPLIT,
      3: Participant.actions.SPLIT,
      4: Participant.actions.HIT,
      5: Participant.actions.DOUBLE,
      6: Participant.actions.SPLIT,
      7: Participant.actions.SPLIT,
      8: Participant.actions.SPLIT,
      9: Participant.actions.SPLIT,
      10: Participant.actions.STAND,
      11: Participant.actions.SPLIT,
    },
    4: {
      2: Participant.actions.SPLIT,
      3: Participant.actions.SPLIT,
      4: Participant.actions.HIT,
      5: Participant.actions.DOUBLE,
      6: Participant.actions.SPLIT,
      7: Participant.actions.SPLIT,
      8: Participant.actions.SPLIT,
      9: Participant.actions.SPLIT,
      10: Participant.actions.STAND,
      11: Participant.actions.SPLIT,
    },
    5: {
      2: Participant.actions.SPLIT,
      3: Participant.actions.SPLIT,
      4: Participant.actions.SPLIT,
      5: Participant.actions.DOUBLE,
      6: Participant.actions.SPLIT,
      7: Participant.actions.SPLIT,
      8: Participant.actions.SPLIT,
      9: Participant.actions.SPLIT,
      10: Participant.actions.STAND,
      11: Participant.actions.SPLIT,
    },
    6: {
      2: Participant.actions.SPLIT,
      3: Participant.actions.SPLIT,
      4: Participant.actions.SPLIT,
      5: Participant.actions.DOUBLE,
      6: Participant.actions.SPLIT,
      7: Participant.actions.SPLIT,
      8: Participant.actions.SPLIT,
      9: Participant.actions.SPLIT,
      10: Participant.actions.STAND,
      11: Participant.actions.SPLIT,
    },
    7: {
      2: Participant.actions.SPLIT,
      3: Participant.actions.SPLIT,
      4: Participant.actions.HIT,
      5: Participant.actions.DOUBLE,
      6: Participant.actions.HIT,
      7: Participant.actions.SPLIT,
      8: Participant.actions.SPLIT,
      9: Participant.actions.STAND,
      10: Participant.actions.STAND,
      11: Participant.actions.SPLIT,
    },
    8: {
      2: Participant.actions.HIT,
      3: Participant.actions.HIT,
      4: Participant.actions.HIT,
      5: Participant.actions.DOUBLE,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.SPLIT,
      9: Participant.actions.SPLIT,
      10: Participant.actions.STAND,
      11: Participant.actions.SPLIT,
    },
    9: {
      2: Participant.actions.HIT,
      3: Participant.actions.HIT,
      4: Participant.actions.HIT,
      5: Participant.actions.DOUBLE,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.SPLIT,
      9: Participant.actions.SPLIT,
      10: Participant.actions.STAND,
      11: Participant.actions.SPLIT,
    },
    10: {
      2: Participant.actions.HIT,
      3: Participant.actions.HIT,
      4: Participant.actions.HIT,
      5: Participant.actions.HIT,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.SPLIT,
      9: Participant.actions.STAND,
      10: Participant.actions.STAND,
      11: Participant.actions.SPLIT,
    },
    11: {
      2: Participant.actions.HIT,
      3: Participant.actions.HIT,
      4: Participant.actions.HIT,
      5: Participant.actions.HIT,
      6: Participant.actions.HIT,
      7: Participant.actions.HIT,
      8: Participant.actions.SPLIT,
      9: Participant.actions.STAND,
      10: Participant.actions.STAND,
      11: Participant.actions.SPLIT,
    },
  },
  SOFT: {
    // Outside key is value of dealers upcard, ace == 11
    // Inside key is total value of players hand, with ace == 11
    2: {
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.HIT,
      16: Participant.actions.HIT,
      17: Participant.actions.HIT,
      18: Participant.actions.DS,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    3: {
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.HIT,
      16: Participant.actions.HIT,
      17: Participant.actions.DOUBLE,
      18: Participant.actions.DS,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    4: {
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.DOUBLE,
      16: Participant.actions.DOUBLE,
      17: Participant.actions.DOUBLE,
      18: Participant.actions.DS,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    5: {
      13: Participant.actions.DOUBLE,
      14: Participant.actions.DOUBLE,
      15: Participant.actions.DOUBLE,
      16: Participant.actions.DOUBLE,
      17: Participant.actions.DOUBLE,
      18: Participant.actions.DS,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    6: {
      13: Participant.actions.DOUBLE,
      14: Participant.actions.DOUBLE,
      15: Participant.actions.DOUBLE,
      16: Participant.actions.DOUBLE,
      17: Participant.actions.DOUBLE,
      18: Participant.actions.DS,
      19: Participant.actions.DS,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    7: {
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.HIT,
      16: Participant.actions.HIT,
      17: Participant.actions.HIT,
      18: Participant.actions.STAND,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    8: {
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.HIT,
      16: Participant.actions.HIT,
      17: Participant.actions.HIT,
      18: Participant.actions.STAND,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    9: {
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.HIT,
      16: Participant.actions.HIT,
      17: Participant.actions.HIT,
      18: Participant.actions.HIT,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    10: {
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.HIT,
      16: Participant.actions.HIT,
      17: Participant.actions.HIT,
      18: Participant.actions.HIT,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
    11: {
      13: Participant.actions.HIT,
      14: Participant.actions.HIT,
      15: Participant.actions.HIT,
      16: Participant.actions.HIT,
      17: Participant.actions.HIT,
      18: Participant.actions.HIT,
      19: Participant.actions.STAND,
      20: Participant.actions.STAND,
      21: Participant.actions.STAND,
    },
  },
}
